import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import NavBar from "@/components/nav/NavBar";

const inter = Inter({subsets: ['latin'], variable: '--font-sans'});

export const metadata: Metadata = {
    title: "Carsties",
    description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
    return (
        <html lang="en" className={cn("font-sans", inter.variable)}>
        <body className={'bg-muted min-h-screen flex flex-col'}>
        <NavBar/>
        <main className="container mx-auto mt-8 flex flex-1 flex-col">
            {children}
          
        </main>

        </body>
        </html>
    );
}
